Intent is to avoid having to re-process 401 challenge with each request.
rjrudin/marklogic-spring-web pull request #1
Opened 2018-01-25 06:30 UTC by kghmanuel

2018-01-25 07:01 UTC, gmarintes approved these changes
code looks okay.
might want to fix the indent on HttpProxy.java line 101.

2018-01-28 22:56 UTC, rjrudin requested changes

2018-01-28 22:56 UTC, rjrudin commented on src/main/java/com/marklogic/spring/security/authentication/MarkLogicAuthenticationManager.java
> +    private RestTemplate prepareRestTemplate(SimpleCredentialsProvider provider) {
I think this needs to be protected in case a client e.g. wants to subclass this and override how the CloseableHttpClient is constructed.

2018-01-28 22:56 UTC, rjrudin commented on src/main/java/com/marklogic/spring/security/authentication/MarkLogicAuthenticationManager.java
> +        final DigestScheme digestAuth = new DigestScheme();
Does this work for basic auth too?

2018-01-28 22:56 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +    private RestOperations getSessionRestTemplate(HttpServletRequest httpRequest) {
Should be protected in case a client wants to subclass this and override the behavior

2018-01-28 22:56 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +    public static final String RESTTEMPLATE_SESSION_KEY = "upstream.restemplate";
I think something marklogic-specific would be good here to guarantee uniqueness - e.g. "com.marklogic.spring.http.proxy.RestTemplate"

2018-01-28 22:56 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +            return null;
Shouldn't this throw an error now, or else an expected NullPointerException will be thrown later?

2018-01-28 22:56 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +        RestOperations client = getSessionRestTemplate(httpRequest);
I am wondering if a boolean would be useful to turn this behavior off - it can be on by default, but in case it doesn't work for someone, a boolean to flip it off would be useful - e.g. "private boolean storeRestTemplatesInSession = true" with a getter/setter.

2018-01-29 12:03 UTC, kghmanuel commented on src/main/java/com/marklogic/spring/security/authentication/MarkLogicAuthenticationManager.java
> +        final DigestScheme digestAuth = new DigestScheme();
no. it does not. fixed.

2018-01-30 08:08 UTC, kghmanuel commented
made several adjustments to simplify the changes. addressed all concerns.

2018-02-09 14:25 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/RestConfig.java
> +    public Boolean getCacheDigest();
A boolean method normally starts with "is" or "has". Looking at how it's used, perhaps it should be named "isDigestCachingEnabled" or "shouldCacheDigest". I think I prefer the former.

2018-02-09 14:25 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +        if ("digest".equalsIgnoreCase(challenge.getType()) && getRestConfig().getCacheDigest()) {
It looks like nothing needs to be done if "getCacheDigest" returns false. So I think the first "if" is to test that, and if it's false, then just return the normal RestTemplate. Else, determine if digest is being used and if so, call prepareDigestTemplate.

2018-02-09 14:25 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +    protected RestTemplate prepareDigestTemplate(CredentialsProvider provider, String realm) {
Looking at this and the newRestTemplate method in RestClient, I think a RestTemplateBuilder interface is warranted, and this logic is non-trivial. Something like this:

RestTemplate buildRestTemplate(RestConfig, CredentialsProvider);

That makes it easy to modify this logic in case anything is wrong with either implementation.

2018-02-09 14:25 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +                    .useSystemProperties()
I noticed this was not in the RestClient.newRestTemplate method, should it be?

2018-02-09 14:25 UTC, rjrudin commented on src/main/java/com/marklogic/spring/http/AuthenticationHeader.java
> +public class AuthenticationHeader {
It seems like the purpose of this class is to extract the digest challenge string and the realm. I think an interface is warranted for this as well, as the logic for doing so isn't trivial. 

How about - AuthenticationHeaderExtractor, with a method of:

AuthenticationHeader extractAuthenticationHeader(RestConfig)

I get nervous when I see a static method for a "plumbing" library like marklogic-spring-web, because that makes it harder for a client to override the functionality. But by defining an interface - which I believe the RestTemplateBuilder below would make use of - it's much easier for a client to customize how the plumbing works.

2018-02-12 03:19 UTC, kghmanuel commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +        if ("digest".equalsIgnoreCase(challenge.getType()) && getRestConfig().getCacheDigest()) {
i had comments before that prefers to have a single return point. will adjust.

2018-02-13 04:28 UTC, kghmanuel commented on src/main/java/com/marklogic/spring/http/proxy/HttpProxy.java
> +    protected RestTemplate prepareDigestTemplate(CredentialsProvider provider, String realm) {
In such a scenario where the implementation is faulty, user already has the flexibility to override the function.

2018-03-08 20:21 UTC, rjrudin commented
@kghmanuel Sorry for the delay, I had a chance to look at the code locally. Take a look at the PR I put together based on your work - https://github.com/rjrudin/marklogic-spring-web/pull/2 

The main change was removing construction of the RestOperations from RestClient/HttpProxy and putting it into DefaultRestOperationsFactory. That keeps RestClient unaware of how a RestOperations is constructed. 

All of your code is in DefaultRestOperationsFactory (DROF). Now, if someone needs to tweak it, they can either extend DROF or write their own code for controlling how a RestOperations is constructed. 

I'm going to close this one, and please let me know if the way the code is organized in that PR works for you.

2018-03-08 20:21 UTC, closed without merging